#!/bin/sh
# Writes event_names.h, the names of the event build (unity_events.c): every
# function of the optimized backend that is not static gets one of its own
# there, so that both builds are in one library. The functions of the API
# become ddnet_ev_*, the others ddnet_ev__*. world_new_universe() keeps its
# name: both builds use the one of the other build (one counter for the
# worlds of both).
#
# Usage: event_names.sh <unity.c.o of the optimized backend>
#
# Run it after adding or removing a function that is not static. A list that
# misses one makes linking a program that uses both builds fail with a
# duplicate symbol (tests/event_diff links both).
set -eu
here=$(cd "$(dirname "$0")" && pwd)
out=$here/event_names.h
{
  echo "/* Generated by event_names.sh from the global symbols of unity.c: the names of the event build. */"
  nm -g --defined-only "$1" | awk '$2 ~ /^[TDBR]$/ {print $3}' | sort -u | grep -v '^world_new_universe$' |
    grep -v '^ddnet_prof_' | while read -r name; do
    case $name in
    ddnet_*) echo "#define $name ddnet_ev_${name#ddnet_}" ;;
    *) echo "#define $name ddnet_ev__$name" ;;
    esac
  done
} > "$out"
echo "wrote $out ($(grep -c '^#define' "$out") names)"
